# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.maxmind.geoip2', 'geoip2', '2.17.0')
require_jar('com.maxmind.db', 'maxmind-db', '2.1.0')
require_jar('org.logstash.filters', 'logstash-filter-geoip', '7.3.0')
